#%RAML 1.0
title: Radio Station
version: v1
baseUri: http://api.samplehost.com

/config:
  get:

/login:
  post:

/nowPlaying:
  get:
  put:

/shows:
  get:
  post:

  /{id}:
    get:
    put:
    delete:

/djs:
  get:
  post:

  /{id}:
    get:
    put:
    delete:
