#%RAML 1.0
title: Radio Station
uses:
  RadioStation: RadioStation.raml
version: v1
baseUri: http://api.samplehost.com

types:
  Config: RadioStation.Config
  NowPlayingInfo: RadioStation.NowPlayingInfo
  DJ: RadioStation.DJ
  Show: RadioStation.Show

/config:
  description: Station configuration.
  get:
    description: Fetch the current station configuration.
    responses:
      200:
        body:
          application/json:
            type: Config
/nowPlaying:
  description: Now playing information.
  get:
    description: Fetch the current now playing information.
    responses:
      200:
        body:
          application/json:
            type: NowPlayingInfo
  put:
    is:  [RadioStation.Secured]
    description: Update the now playing information.
    body:
      application/json:
        type: NowPlayingInfo
/shows:
  type:  { RadioStation.Collection: {item : Show} }
  description: Retrieve/edit all of the station's shows.
  get:
    is:  [RadioStation.FilterableByDayOfWeek, RadioStation.FilterableByIsActive]
  /{id}:
    type:  { RadioStation.Member: {item : Show} }
    description: Retrieve/edit the details for a specific show.
/djs:
  type:  { RadioStation.Collection: {item : DJ} }
  description: Retrieve/edit DJs associated with the station.
  get:
    is:  [RadioStation.FilterableByIsActive]
  /{id}:
    type:  { RadioStation.Member: {item : DJ} }
    description: Retrieve/edit the details for a specific station DJ.
