#%RAML 1.0
title: Radio Station API
uses:
  RadioStation: RadioStation.raml
version: v1
baseUri: http://api.samplehost.com

types:
  Config: RadioStation.Config
  NowPlayingInfo: RadioStation.NowPlayingInfo
  DJ: RadioStation.DJ
  Show: RadioStation.Show

/config:
  get:
    description: Fetch the current station configuration.
    responses:
      200:
        body:
          application/json:
            type: Config
/nowPlaying:
  get:
    description: Fetch the current now playing information.
    responses:
      200:
        body:
          application/json:
            type: NowPlayingInfo
  patch:
    is:  [RadioStation.Secured]
    description: Apply a partial update to the now playing information.
    body:
      application/json:
        type: NowPlayingInfo
  put:
    is:  [RadioStation.Secured]
    description: Update the now playing information.
    body:
      application/json:
        type: NowPlayingInfo
/shows:
  type:  { RadioStation.Collection: {item : Show} }
  get:
    is:  [RadioStation.FilterableByDayOfWeek, RadioStation.FilterableByIsActive]
    description: Retrieve all of the station's shows.
  /{id}:
    description: Retrieve the details for a specific show.
    type:  { RadioStation.Member: {item : Show} }
/djs:
  type:  { RadioStation.Collection: {item : DJ} }
  get:
    is:  [RadioStation.FilterableByIsActive]
    description: Retrieve all of the DJs associated with the station.
  /{id}:
    description: Retrieve the details for a specific station DJ.
    type:  { RadioStation.Member: {item : DJ} }
