#%RAML 1.0 Library
traits:
  FilterableByDayOfWeek:
    queryParameters:
      dayOfWeek:
        enum:
          - mon
          - tues
          - wed
          - thurs
          - fri
          - sat
          - sun
  FilterableByIsActive:
    queryParameters:
      isActive: boolean
resourceTypes:
  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
    post:
      body:
        application/json:
          type: <<item>>
  Member:
    put:
      body:
        application/json:
          type: <<item>>
    patch:
      body:
        application/json:
          type: <<item>>
    delete:
      responses:
        204:
types:
  BaseObject:
    properties:
      id: string
  DJ:
    type: BaseObject
    properties:
      handle: string
      firstName: string
      lastName: string
      showId: string
      isActive: boolean
    example:
      id: "1"
      handle: Overfiend
      firstName: Louis
      lastName: Overfiend
      showId: "1"
      isActive: true
  Show:
    type: BaseObject
    properties:
      name: string
      description: string
      djId: string
      broadcastInfo: object
      nextBroadcastTime: integer
      avatarUrl: string
      soundcloudUrl: string
      isActive: boolean
    example:
      id: "5"
      name: The Greenroom
      description: A classically­ trained keyboardist and working musician based in Chicago, STUNNA (aka J. Cappo) has crafted his own unique sound within the fast­paced world of Drum + Bass music
      djId: "2"
      broadcastInfo:
        location: Chicago, IL, USA
        dayOfWeek: Wednesday
        startTime: 14:00
        endTime: 17:00
      nextBroadcastTime: 1490814000
      avatarUrl: http://bassdrive.com/img/radio_schedule_entries/image/original/stunnagreenroompromo1nufinalhalf-74.jpg
      soundcloudUrl: https://soundcloud.com/stunna
      isActive: true
